version: "2"

run:
  timeout: 5m

linters:
  exclusions:
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gocyclo
          - errcheck
          - dupl
          - gosec
      # Run some linter only for test files by excluding its issues for everything else.
      - path-except: _test\.go
        linters:
          - forbidigo
      # Exclude known linters from partially hard-vendored code,
      # which is impossible to exclude via `nolint` comments.
      # `/` will be replaced by the current OS file path separator to properly work on Windows.
      - path: internal/hmac/
        text: "weak cryptographic primitive"
        linters:
          - gosec
      # Exclude some `staticcheck` messages.
      - linters:
          - staticcheck
        text: "SA9003:"
      # Exclude `lll` issues for long lines with `go:generate`.
      - linters:
          - lll
        source: "^//go:generate "
  enable:
    - govet
    - revive
    - gosec
    - gocyclo
    - unconvert
    - goconst
    - misspell
    - lll
    - unparam
    - ineffassign
    - staticcheck
  disable:
    - errcheck
  settings:
    govet:
      enable:
        - shadow
    gocyclo:
      min-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 2
      min-occurrences: 2
    revive:
      enable-default-rules: true
    misspell:
      locale: US
    lll:
      line-length: 120
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
      disabled-checks:
        - wrapperFunc
        - ifElseChain
        - octalLiteral

formatters:
  settings:
    goimports:
      local-prefixes:
        - github.com/investigato/go-psrp

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
